# Config file for automatic testing at travis-ci.org

language: python
  - "3.7"
sudo: required
before_install:
  - sudo apt-get update
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes
  - conda update -q conda
  - conda install conda-build
  - conda install anaconda-client
  - conda install pytest-cov
  - pip install coveralls
  - conda build .
  - conda install --use-local uit
  - conda info -a
script:
  - pytest -v --cov=uit tests
after_success:
  - coveralls
