# conda environment file includes packages needed for testing
# create a conda virtual env using:
#   conda env create -n myenv --file environment.yml
#   conda activate myenv
#   python setup.py develop

name: uit

channels:
  - erdc

dependencies:
  - flask
  - pyyaml
  - requests
  - dodcerts

  # for notebooks
  - jupyterlab
  - nodejs
  - pandas
  - panel
  - param

  # for tests
  - pytest
  - pytest-cov
