{% set data = load_setup_py_data() %}

package:
  name: {{ data['name'] }}
  version: {{ data['version'] }}

source:
  path: ..

build:
  # If the installation is complex, or different between Unix and Windows, use
  # separate bld.bat and build.sh files instead of this key.  Add the line
  # "skip: True  # [py<35]" (for example) to limit to Python 3.5 and newer, or
  # "skip: True  # [not win]" to limit to Windows.
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
      # dependencies are defined in setup.py
      {% for dep in data['install_requires'] %}
      - {{ dep.lower() }}
      {% endfor %}
      {% for dep in data['extras_requires']['recommended'] %}
      - {{ dep.lower() }}
      {% endfor %}

test:
  imports:
    - uit

about:
  home: https://github.com/dharhas/uit
  summary: Python wrapper for DoD HPCMP UIT+ rest interface
