{% set data = load_setup_py_data() %}

package:
  name: pyuit
  version: {{ data['version'] }}

source:
  path: ..

build:
  noarch: python
  number: 2
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python=3.7*
    - setuptools
  run:
    - python

    # dependencies are defined in setup.py
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}
    {% for dep in data['extras_require']['guitools'] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  imports:
    - uit
    - uit.gui_tools

about:
  home: https://github.com/erdc/pyuit
  summary: Python wrapper for DoD HPCMP UIT+ rest interface
